mod converter;
pub mod error;
mod verify;

include!(concat!(env!("OUT_DIR"), "/part_stark_vk_registry.rs"));

use p3_bn254_fr::Bn254Fr;
use p3_field::{FieldAlgebra, PrimeField};
use substrate_bn::Fr;

use alloc::vec::Vec;
use sha2::{Digest, Sha256};
use zkm_primitives::io::hash_public_values_blake3_bn254;
use zkm_recursion_core::stark::KoalaBearPoseidon2Outer;
use zkm_stark::PartStarkVerifyingKey;

use crate::{decode_zkm_vkey_hash, error::Error, hash_public_inputs};
pub(crate) use converter::{load_groth16_proof_from_bytes, load_groth16_verifying_key_from_bytes};
pub(crate) use verify::*;

use error::Groth16Error;

#[cfg(feature = "ark")]
use crate::ArkGroth16Error;
#[cfg(feature = "ark")]
use ark_bn254::Bn254;
#[cfg(feature = "ark")]
use ark_groth16::{r1cs_to_qap::LibsnarkReduction, Groth16};
#[cfg(feature = "ark")]
use zkm_sdk::ZKMProofWithPublicValues;
#[cfg(feature = "ark")]
pub mod ark_converter;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Groth16VkPrefixError {
    InvalidData,
    Mismatch,
}

pub(crate) fn check_groth16_vk_prefix(
    proof: &[u8],
    groth16_vk: &[u8],
) -> Result<(), Groth16VkPrefixError> {
    if proof.len() < 4 {
        return Err(Groth16VkPrefixError::InvalidData);
    }

    // Hash the vk and get the first 4 bytes.
    let groth16_vk_hash: [u8; 4] = Sha256::digest(groth16_vk)[..4]
        .try_into()
        .map_err(|_| Groth16VkPrefixError::InvalidData)?;

    // Check to make sure that this proof was generated by the groth16 proving key corresponding to
    // the given groth16_vk.
    //
    // Ziren prepends the raw Groth16 proof with the first 4 bytes of the groth16 vkey to
    // facilitate this check.
    if groth16_vk_hash != proof[..4] {
        return Err(Groth16VkPrefixError::Mismatch);
    }

    Ok(())
}

/// A verifier for Groth16 zero-knowledge proofs.
#[derive(Debug)]
pub struct Groth16Verifier;
impl Groth16Verifier {
    /// Verifies a Ziren Groth16 proof, as generated by the Ziren SDK.
    ///
    /// # Arguments
    ///
    /// * `proof` - The proof bytes.
    /// * `public_inputs` - The Ziren public inputs.
    /// * `zkm_vkey_hash` - The Ziren vkey hash.
    ///   This is generated in the following manner:
    ///
    /// ```ignore
    /// use zkm_sdk::ProverClient;
    /// let client = ProverClient::new();
    /// let (pk, vk) = client.setup(ELF);
    /// let zkm_vkey_hash = vk.bytes32();
    /// ```
    /// * `groth16_vk` - The Groth16 verifying key bytes.
    ///   Usually this will be the [`static@crate::GROTH16_VK_BYTES`] constant, which is the Groth16
    ///   verifying key for the current Ziren version.
    ///
    /// # Returns
    ///
    /// A success [`Result`] if verification succeeds, or a [`Groth16Error`] if verification fails.
    pub fn verify(
        proof: &[u8],
        zkm_public_inputs: &[u8],
        zkm_vkey_hash: &str,
        groth16_vk: &[u8],
    ) -> Result<(), Groth16Error> {
        check_groth16_vk_prefix(proof, groth16_vk).map_err(|e| match e {
            Groth16VkPrefixError::InvalidData => Groth16Error::GeneralError(Error::InvalidData),
            Groth16VkPrefixError::Mismatch => Groth16Error::Groth16VkeyHashMismatch,
        })?;

        let zkm_vkey_hash = decode_zkm_vkey_hash(zkm_vkey_hash)?;

        Self::verify_gnark_proof(
            &proof[4..],
            &[zkm_vkey_hash, hash_public_inputs(zkm_public_inputs)],
            groth16_vk,
        )
    }

    /// Verifies a Ziren Groth16 proof, as generated by the Ziren SDK.
    ///
    /// # Arguments
    ///
    /// * `proof` - The proof bytes.
    /// * `public_inputs` - The Ziren public inputs.
    /// * `zkm_vkey_hash` - The Ziren vkey hash.
    ///   This is generated in the following manner:
    ///
    /// ```ignore
    /// use zkm_sdk::ProverClient;
    /// let client = ProverClient::new();
    /// let (pk, vk) = client.setup(ELF);
    /// let zkm_vkey_hash = vk.bytes32();
    /// ```
    /// * `imm_groth16_vk` - The Groth16 verifying key bytes.
    ///   Usually this will be the [`static@crate::IMM_GROTH16_VK_BYTES`] constant,
    ///   which is the Groth16 verifying key for all Ziren versions.
    /// * `part_stark_vk` - The partial STARK verifying key bytes.
    ///   Usually this will be the [`static@crate::PART_STARK_VK_BYTES`] constant,
    ///   which is the partial STARK verifying key for the current Ziren version.
    ///   You can also obtain the given version of the partial STARK vk through function:
    /// ```ignore
    /// let part_stark_vk = Groth16Verifier::get_part_stark_vk(zkm_circuit_version);
    /// ```
    ///
    /// # Returns
    ///
    /// A success [`Result`] if verification succeeds, or a [`Groth16Error`] if verification fails.
    pub fn verify_by_imm_groth16_vk(
        proof: &[u8],
        zkm_public_inputs: &[u8],
        zkm_vkey_hash: &str,
        imm_groth16_vk: &[u8],
        part_stark_vk: &[u8],
    ) -> Result<(), Groth16Error> {
        check_groth16_vk_prefix(proof, imm_groth16_vk).map_err(|e| match e {
            Groth16VkPrefixError::InvalidData => Groth16Error::GeneralError(Error::InvalidData),
            Groth16VkPrefixError::Mismatch => Groth16Error::Groth16VkeyHashMismatch,
        })?;

        let zkm_vkey_hash = decode_zkm_vkey_hash(zkm_vkey_hash)?;
        let zkm_vkey_hash = hash_vkey_with_part_vk(&zkm_vkey_hash, part_stark_vk)?;

        Self::verify_gnark_proof(
            &proof[4..],
            &[zkm_vkey_hash, hash_public_values_blake3_bn254(zkm_public_inputs)],
            imm_groth16_vk,
        )
    }

    /// Get the partial STARK verifying key for a given version.
    /// version: The version of the circuit, e.g. "v1.0.0"
    pub fn get_part_stark_vk(zkm_circuit_version: &str) -> &'static [u8] {
        BUNDLED_PART_STARK_VKS
            .iter()
            .find_map(|(version, bytes)| (*version == zkm_circuit_version).then_some(*bytes))
            .unwrap_or_else(|| {
                panic!("unsupported bundled part_stark_vk version: {zkm_circuit_version}")
            })
    }

    #[cfg(feature = "ark")]
    pub fn ark_verify(
        proof_with_pub_values: &ZKMProofWithPublicValues,
        vkey_hash: &str,
        groth16_vk: &[u8],
    ) -> Result<bool, ArkGroth16Error> {
        let ark_proof = crate::convert_ark(proof_with_pub_values, vkey_hash, groth16_vk)?;

        Groth16::<Bn254, LibsnarkReduction>::verify_proof(
            &ark_proof.groth16_vk,
            &ark_proof.proof,
            &ark_proof.public_inputs,
        )
        .map_err(|_| ArkGroth16Error::ProofVerificationFailed)
    }

    #[cfg(feature = "ark")]
    pub fn ark_verify_by_imm_groth16_vk(
        proof_with_pub_values: &ZKMProofWithPublicValues,
        vkey_hash: &str,
        imm_groth16_vk: &[u8],
        part_stark_vk: &[u8],
    ) -> Result<bool, ArkGroth16Error> {
        let ark_proof = crate::convert_ark_imm_wrap_vk(
            proof_with_pub_values,
            vkey_hash,
            imm_groth16_vk,
            part_stark_vk,
        )?;

        Groth16::<Bn254, LibsnarkReduction>::verify_proof(
            &ark_proof.groth16_vk,
            &ark_proof.proof,
            &ark_proof.public_inputs,
        )
        .map_err(|_| ArkGroth16Error::ProofVerificationFailed)
    }

    /// Verifies a Gnark Groth16 proof using raw byte inputs.
    ///
    /// WARNING: if you're verifying a Ziren proof, you should use [`verify`] instead.
    /// This is a lower-level verification method that works directly with raw bytes rather than
    /// the Ziren SDK's data structures.
    ///
    /// # Arguments
    ///
    /// * `proof` - The raw Groth16 proof bytes (without the 4-byte vkey hash prefix)
    /// * `public_inputs` - The public inputs to the circuit
    /// * `groth16_vk` - The Groth16 verifying key bytes
    ///
    /// # Returns
    ///
    /// A [`Result`] containing unit `()` if the proof is valid,
    /// or a [`Groth16Error`] if verification fails.
    ///
    /// # Note
    ///
    /// This method expects the raw proof bytes without the 4-byte vkey hash prefix that
    /// [`verify`] checks. If you have a complete proof with the prefix, use [`verify`] instead.    
    pub fn verify_gnark_proof(
        proof: &[u8],
        public_inputs: &[[u8; 32]],
        groth16_vk: &[u8],
    ) -> Result<(), Groth16Error> {
        let proof = load_groth16_proof_from_bytes(proof)?;
        let groth16_vk = load_groth16_verifying_key_from_bytes(groth16_vk)?;

        let public_inputs = public_inputs
            .iter()
            .map(|input| {
                Fr::from_slice(input).map_err(|e| {
                    Groth16Error::InputConversion(format!("Failed to convert public input: {e}"))
                })
            })
            .collect::<Result<Vec<_>, _>>()?;

        verify_groth16_algebraic(&groth16_vk, &proof, &public_inputs)
    }
}

// Combine the base vkey hash with the `vk_commitment` and `pc_start` using a Poseidon2 permutation.
pub fn hash_vkey_with_part_vk(
    zkm_vkey_hash: &[u8; 32],
    part_vk: &[u8],
) -> Result<[u8; 32], Groth16Error> {
    let part_vk: PartStarkVerifyingKey<KoalaBearPoseidon2Outer> = bincode::deserialize(part_vk)
        .map_err(|_| Groth16Error::GeneralError(Error::InvalidData))?;
    let zkm_vkey_hash = bytes_to_bn254fr(zkm_vkey_hash);
    let vk_hash = zkm_recursion_core::hash_vkey_with_part_vk(&part_vk, zkm_vkey_hash);
    bn254fr_to_fr(vk_hash)
}

pub fn bn254fr_to_fr(value: Bn254Fr) -> Result<[u8; 32], Groth16Error> {
    let big = value.as_canonical_biguint();
    let big_bytes = big.to_bytes_be();
    if big_bytes.len() > 32 {
        return Err(Groth16Error::GeneralError(Error::InvalidData));
    }

    let mut bytes = [0u8; 32];
    bytes[32 - big_bytes.len()..].copy_from_slice(&big_bytes);
    Ok(bytes)
}

pub fn bytes_to_bn254fr(bytes: &[u8; 32]) -> Bn254Fr {
    let mut acc = Bn254Fr::ZERO;
    let base = Bn254Fr::from_canonical_u32(256);
    for byte in bytes.iter() {
        acc = acc * base + Bn254Fr::from_canonical_u32(*byte as u32);
    }
    acc
}
