name: Scheduled CI

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Cargo Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: |
          set -e
          for pkg in zkm-core-machine zkm-sdk zkm-verifier; do
            cargo test -r -p $pkg
          done
        env:
          RUSTFLAGS: "-C target-cpu=native"
